"""201907231136

Revision ID: 316c22686ebf
Revises: 5f1363458ca8
Create Date: 2019-07-23 11:38:13.900833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316c22686ebf'
down_revision = '5f1363458ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
