"""201907231135

Revision ID: 5f1363458ca8
Revises: 2ce1fb8ed0fa
Create Date: 2019-07-23 11:35:15.999009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1363458ca8'
down_revision = '2ce1fb8ed0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
