"""201907231138

Revision ID: 8d2387ec99d5
Revises: 0f3b87e5f727
Create Date: 2019-07-23 11:43:02.345210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2387ec99d5'
down_revision = '0f3b87e5f727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('time_stamp', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'time_stamp')
    # ### end Alembic commands ###
